import { Command } from "commander";
import { createAgentCommand } from "./commands/agent.ts";
import { createAskCommand } from "./commands/ask.ts";
import { createCodexCommand } from "./commands/codex.ts";
import { createCommandCommand } from "./commands/command.ts";
import { createConfigCommand } from "./commands/config.ts";
import { createCopilotCommand } from "./commands/copilot.ts";
import { createDecideCommand } from "./commands/decide.ts";
import { createDigestCommand } from "./commands/digest.ts";
import { createHookCommand } from "./commands/hook.ts";
import { createImagineCommand } from "./commands/imagine.ts";
import { createLogCommand } from "./commands/log.ts";
import { createMigrateCommand } from "./commands/migrate.ts";
import { createModelsCommand } from "./commands/models.ts";
import { createMotionCommand } from "./commands/motion.ts";
import { createMusicCommand } from "./commands/music.ts";
import { createPromptCommand } from "./commands/prompt.ts";
import { createRuleCommand } from "./commands/rule.ts";
import { createScheduleCommand } from "./commands/schedule.ts";
import { createSkillCommand } from "./commands/skill.ts";
import { createSyncCommand } from "./commands/sync.ts";
import { createTelegramCommand } from "./commands/telegram.ts";
import { createTranscribeCommand } from "./commands/transcribe.ts";
import { createVideoCommand } from "./commands/video.ts";

const program = new Command();

program.name("cc-hub").description("All-in-one AI CLI — logs, digest, multi-model").version("0.1.0");

program.addCommand(createLogCommand());
program.addCommand(createMigrateCommand());
program.addCommand(createDigestCommand());
program.addCommand(createScheduleCommand());
program.addCommand(createConfigCommand());
program.addCommand(createAskCommand());
program.addCommand(createDecideCommand());
program.addCommand(createImagineCommand());
program.addCommand(createVideoCommand());
program.addCommand(createMotionCommand());
program.addCommand(createTranscribeCommand());
program.addCommand(createPromptCommand());
program.addCommand(createSyncCommand());
program.addCommand(createTelegramCommand());
program.addCommand(createSkillCommand());
program.addCommand(createCommandCommand());
program.addCommand(createRuleCommand());
program.addCommand(createHookCommand());
program.addCommand(createAgentCommand());
program.addCommand(createCopilotCommand());
program.addCommand(createCodexCommand());
program.addCommand(createModelsCommand());
program.addCommand(createMusicCommand());

export { program };
